### ISSUE TITLE
29. jaanuari todo

### ISSUE THREAD

**Issue by mitselek** [i-b-c/KGS#120]
- [x] performance.artist collection kustutada ja x_artist väli nimetada ümber 'artist'iks;
- [x] Annika ei saa artikleid ajalises järjekorras (viimati redigeeritud, viimati avaldatud);
- [X] Kas saaks sedasi, et artikli autorid ja lavastuste artistid tekiksid tekstivälja baasil automaatselt? pigem ei, eelistavad tekstivälju;
- [x] Magasini artikli autori valik baseerugu fullname väljal (praegu eesnimi);
- [x] performance seotud tööd on strapis x_other_works. Kaie soovib siia käsitsi valida teisi performanceid. Issue #122;
- [x] sündmuse juurde teha automaatne otsiväli "artisti nimi / lavastuse nimi" - täita ka tagasiulatuvalt;
        tegu on üldise vajadusega *display* välja järele (nt. peformance juurde lavastuste valimisel)
- [x] **Ülapealkiri** tekib ise, kui sündmus siduda ülemsündmusega ja salvestada. On ka käsitsi täidetav/muudetav. Issue #124 ;
- [ ] **[objektidest duplikaadi tegemine](https://stackoverflow.com/questions/60522438/how-to-duplicate-clone-a-record-in-strapi)**;
- [ ] kui performance külge lisada valikust event, kas on võimalik, et ta "varastab" selle mõnelt teiselt performancelt;
- [x] artikli persoonide publitseerimisega Annika ei taha tegeleda (autopublish neile);
- [x] @mpennaste onlain evendi nupp klikitav/mitte;
- [x] newscastile "publitseeritud" väli; kui see on täitmata, siis kasutada "published_at".
- [x] miks magasinil ja performancil slug-i automaatselt ei tekkinud
- [x] CSS-is magazine article sees pildil max kõrgus

**Comment by LiisKasper** [comment]
sündmuse juurde teha automaatne otsiväli "artisti nimi / lavastuse nimi" - täita ka tagasiulatuvalt;
tegu on üldise vajadusega display välja järele (nt. peformance juurde lavastuste valimisel) 
- tegime välja search_field, mida saavad täita oma tahtmist mööda, täitub ise, kui midagi kirjas pole
